=== re-motion/Framework/working/Remotion/Web/Core/Schemas/UrlMapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:m="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    targetNamespace="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0" 
    xml:lang="en">

  <!--<xs:import namespace="http://www.re-motion.org/Types" schemaLocation="Types.xsd" />-->

  <xs:element name="urlMapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="add" type="m:mappingEntry" maxOccurs="unbounded" />
      </xs:sequence>
	    <xs:attribute name="application" type="m:requiredStringType" use="optional" />
    </xs:complexType>
    
    <xs:key name="resourceKey">
      <xs:selector xpath="m:add" />
      <xs:field xpath="@resource" />
    </xs:key>
    
    <xs:unique name="idUnique">
      <xs:selector xpath="m:add"/>
      <xs:field xpath="@id"/>
    </xs:unique>
  </xs:element>

  <xs:complexType name="mappingEntry">
    <xs:attribute name="id" type="m:requiredStringType" use="optional" />
    <xs:attribute name="type" type="m:dotNetType" use="required" />
    <xs:attribute name="resource" type="m:requiredStringType" use="required" />
  </xs:complexType>
  
	<xs:simpleType name="requiredStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	
  <xs:simpleType name="dotNetType">
    <xs:restriction base="m:requiredStringType">
      <!--  Class, Assembly; Namespace.Class, Assembly; Namespace.Namespace.Class, Assembly; 
            Class+Class, Assembly; Namespace.Class+Class, Assembly; Namespace.Namespace.Class+Class, Assembly
            Class,Assembly; Namespace.Class,Assembly; Namespace.Namespace.Class,Assembly; 
            Class+Class,Assembly; Namespace.Class+Class,Assembly; Namespace.Namespace.Class+Class,Assembly -->
      <xs:pattern value="(\p{L}[\p{L}\d]*\.)*(\p{L}[\p{L}\d]*\+)*(\p{L}[\p{L}\d]*),\s?([\p{L}\d]+\.)*([\p{L}\d]+)" />

      <!--  Class; Namespace.Class; Namespace.Namespace.Class; 
            Class+Class; Namespace.Class+Class; Namespace.Namespace.Class+Class -->
      <xs:pattern value="(\p{L}[\p{L}\d]*\.)*(\p{L}[\p{L}\d]*\+)*(\p{L}[\p{L}\d]*)" />

      <!--  Namespace::Class; Namespace.Namespace::Class; 
            Namespace::Class+Class; Namespace::Namespace.Class+Class -->
      <xs:pattern value="(\p{L}[\p{L}\d]*\.)*(\p{L}[\p{L}\d]*::)(\p{L}[\p{L}\d]*\.)*(\p{L}[\p{L}\d]*\+)*(\p{L}[\p{L}\d]*)" />
    </xs:restriction>				
	</xs:simpleType>

</xs:schema>

=== re-motion/Framework/working/Remotion/Web/Development.WebTesting.TestSite/UrlMapping.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<urlMapping
    application="WxeTest"
    xmlns="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0 UrlMapping.xsd">

  <add id="AnchorTest" type="Remotion.Web.Development.WebTesting.TestSite::AnchorTestFunction" resource="~/AnchorTest.wxe" />
  <add id="CommandTest" type="Remotion.Web.Development.WebTesting.TestSite::CommandTestFunction" resource="~/CommandTest.wxe" />
  <add id="DropDownListTest" type="Remotion.Web.Development.WebTesting.TestSite::DropDownListTestFunction" resource="~/DropDownListTest.wxe" />
  <add id="DropDownMenuTest" type="Remotion.Web.Development.WebTesting.TestSite::DropDownMenuTestFunction" resource="~/DropDownMenuTest.wxe" />
  <add id="ImageButtonTest" type="Remotion.Web.Development.WebTesting.TestSite::ImageButtonTestFunction" resource="~/ImageButtonTest.wxe" />
  <add id="InfrastructureTests" type="Remotion.Web.Development.WebTesting.TestSite::InfrastructureTestsFunction" resource="~/InfrastructureTests.wxe" />
  <add id="ListMenuTest" type="Remotion.Web.Development.WebTesting.TestSite::ListMenuTestFunction" resource="~/ListMenuTest.wxe" />
  <add id="TabbedMenuTest" type="Remotion.Web.Development.WebTesting.TestSite::TabbedMenuTestFunction" resource="~/TabbedMenuTest.wxe" />
  <add id="TabbedMultiViewTest" type="Remotion.Web.Development.WebTesting.TestSite::TabbedMultiViewTestFunction" resource="~/TabbedMultiViewTest.wxe" />
  <add id="TextBoxTest" type="Remotion.Web.Development.WebTesting.TestSite::TextBoxTestFunction" resource="~/TextBoxTest.wxe" />
  <add id="TreeViewTest" type="Remotion.Web.Development.WebTesting.TestSite::TreeViewTestFunction" resource="~/TreeViewTest.wxe" />
  <add id="WebButtonTest" type="Remotion.Web.Development.WebTesting.TestSite::WebButtonTestFunction" resource="~/WebButtonTest.wxe" />
  <add id="WebTabStripTest" type="Remotion.Web.Development.WebTesting.TestSite::WebTabStripTestFunction" resource="~/WebTabStripTest.wxe" />

  <add id="MultiWindowTest_Main" type="Remotion.Web.Development.WebTesting.TestSite::MultiWindowTest.MainFunction"
      resource="~/MultiWindowTest/Main.wxe" />
  <add id="MultiWindowTest_Frame" type="Remotion.Web.Development.WebTesting.TestSite::MultiWindowTest.FrameFunction"
      resource="~/MultiWindowTest/Frame.wxe" />
  <add id="MultiWindowTest_Window" type="Remotion.Web.Development.WebTesting.TestSite::MultiWindowTest.WindowFunction"
      resource="~/MultiWindowTest/Window.wxe" />
</urlMapping>

=== re-motion/Framework/working/SecurityManager/Clients.Web.Test/UrlMapping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This file is part of re-strict (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! This program is free software; you can redistribute it and/or modify
 ! it under the terms of the GNU Affero General Public License version 3.0 
 ! as published by the Free Software Foundation.
 ! 
 ! This program is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Affero General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Affero General Public License
 ! along with this program; if not, see http://www.gnu.org/licenses.
 ! 
 ! Additional permissions are listed in the file re-motion_exceptions.txt.
-->
<urlMapping
    xmlns="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0 UrlMapping.xsd">

  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditTenantFormFunction" resource="EditTenant.wxe" />
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditGroupFormFunction" resource="EditGroup.wxe" />
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditUserFormFunction" resource="EditUser.wxe" />
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditGroupTypeFormFunction" resource="EditGroupType.wxe" />
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditPositionFormFunction" resource="EditPosition.wxe" />

  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.TenantListFormFunction" resource="TenantList.wxe" id="TenantList"/>
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.GroupListFormFunction" resource="GroupList.wxe" id="GroupList"/>
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.UserListFormFunction" resource="UserList.wxe" id="UserList" />
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.GroupTypeListFormFunction" resource="GroupTypeList.wxe" id="GroupTypeList"/>
  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.PositionListFormFunction" resource="PositionList.wxe" id="PositionList"/>

  <add type="Remotion.SecurityManager.Clients.Web::WxeFunctions.AccessControl.SecurableClassDefinitionListFormFunction" resource="SecurableClassDefinitionList.wxe" id="SecurableClassDefinitionList"/>
</urlMapping>

=== re-motion/Framework/Remotion/Web/Development.WebTesting.TestSite.Shared/UrlMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<urlMapping
    application="WxeTest"
    xmlns="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0 UrlMapping.xsd">

  <add id="AnchorTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::AnchorTestFunction" resource="~/AnchorTest.wxe" />
  <add id="CommandTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::CommandTestFunction" resource="~/CommandTest.wxe" />
  <add id="CoypuElementScopeFindExtensionsTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::CoypuElementScopeFindExtensionsTestFunction" resource="~/CoypuElementScopeFindExtensionsTest.wxe" />
  <add id="DirtyStateTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::DirtyStates.DirtyStateRootFunction" resource="~/DirtyStateTest.wxe" />
  <add id="DropDownListTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::DropDownListTestFunction" resource="~/DropDownListTest.wxe" />
  <add id="DropDownMenuTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::DropDownMenuTestFunction" resource="~/DropDownMenuTest.wxe" />
  <add id="ElementScopeTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::ElementScopeTestFunction" resource="~/ElementScopeTest.wxe" />
  <add id="GenericTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::GenericTestFunction" resource="~/GenericTest.wxe" />
  <add id="ImageButtonTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::ImageButtonTestFunction" resource="~/ImageButtonTest.wxe" />
  <add id="InfrastructureTests" type="Remotion.Web.Development.WebTesting.TestSite.Shared::InfrastructureTestsFunction" resource="~/InfrastructureTests.wxe" />
  <add id="ListMenuTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::ListMenuTestFunction" resource="~/ListMenuTest.wxe" />
  <add id="RequestErrorDetectionStrategyTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::RequestErrorDetectionStrategyTestFunction" resource="~/RequestErrorDetectionStrategyTest.wxe" />
  <add id="ScreenshotTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::ScreenshotTestFunction" resource="~/ScreenshotTest.wxe" />
  <add id="TabbedMenuTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::TabbedMenuTestFunction" resource="~/TabbedMenuTest.wxe" />
  <add id="TabbedMultiViewTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::TabbedMultiViewTestFunction" resource="~/TabbedMultiViewTest.wxe" />
  <add id="TextBoxTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::TextBoxTestFunction" resource="~/TextBoxTest.wxe" />
  <add id="TreeViewTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::TreeViewTestFunction" resource="~/TreeViewTest.wxe" />
  <add id="WebButtonTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::WebButtonTestFunction" resource="~/WebButtonTest.wxe" />
  <add id="WebTabStripTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::WebTabStripTestFunction" resource="~/WebTabStripTest.wxe" />
  <add id="BrowserSessionTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::BrowserSessionTestFunction" resource="~/BrowserSessionTest.wxe" />
  <add id="PlatformTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::PlatformTestFunction" resource="~/PlatformTest.wxe" />
  <add id="CompletionDetectionStrategyTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::CompletionDetectionStrategyTestFunction" resource="~/CompletionDetectionStrategyTest.wxe" />
  <add id="SmartPageErrorTest" type="Remotion.Web.Development.WebTesting.TestSite.Shared::SmartPageErrorTestFunction" resource="~/SmartPageErrorTest.wxe" />

  <add id="MultiWindowTest_Main" type="Remotion.Web.Development.WebTesting.TestSite.Shared::MultiWindowTest.MainFunction"
       resource="~/MultiWindowTest/Main.wxe" />
  <add id="MultiWindowTest_Frame" type="Remotion.Web.Development.WebTesting.TestSite.Shared::MultiWindowTest.FrameFunction"
       resource="~/MultiWindowTest/Frame.wxe" />
  <add id="MultiWindowTest_Window" type="Remotion.Web.Development.WebTesting.TestSite.Shared::MultiWindowTest.WindowFunction"
       resource="~/MultiWindowTest/Window.wxe" />
</urlMapping>

=== re-motion/Framework/working/Remotion/Web/Test/UrlMapping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<urlMapping
    application="WxeTest"
    xmlns="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0 UrlMapping.xsd">
  <add type="Remotion.Web.Test::ExecutionEngine.SessionWxeFunction" resource="session.wxe"/>
  <add type="Remotion.Web.Test::ExecutionEngine.ProfilingWxeFunction" resource="prof.wxe"/>
  <add type="Remotion.Web.Test::ExecutionEngine.RedirectedWxeFunction" resource="redirected.wxe"/>
  <add type="Remotion.Web.Test::UpdatePanelTests.SutFunction" resource="UpdatePanelTests/Sut.wxe"/>
  <add type="Remotion.Web.Test::ExecutionEngine.ShowUserControlFormFunction" resource="ShowUserControl.wxe"/>
  <add type="Remotion.Web.Test::IFrameSupport.MainFunction" resource="Main.wxe"/>
  <add type="Remotion.Web.Test::IFrameSupport.FrameContentFunction" resource="FrameContent.wxe"/>
  <add type="Remotion.Web.Test::ExecutionEngine.ExceptionHandling.TestFunction" resource="ExceptionHandlingTest.wxe"/>
  <!--
		<add type="Remotion.Web.Test.SampleWxeFunction,Remotion.Web.Test" resource="sample.wxe"/>
		<add type="Remotion.Web.Test.SampleWxeFunction,Remotion.Web.Test" resource="sample_old.wxe"/>
-->

  <!--
		<add type="S8essionWxeFunction" resource="session.wxe1"/>
		<add type="SessionWxeFunction+C8lass" resource="session.wxe2"/>
		<add type="R8ubicon.PageTransition.S8essionWxeFunction+C8lass" resource="session.wxe3"/>
		<add type="Remotion.Web.Test.MultiplePostbackCatcherWxeFunction,Remotion.Web.Test" resource="mpc.wxe1"/>
		<add type="Remotion.Web.Test.MultiplePostbackCatcherWxeFunction+Class, Remotion.Web.Test" resource="mpc.wxe2"/>
		<add type="MultiplePostbackCatcherWxeFunction, Remotion.Web.Test" resource="mpc.wxe3"/>
		<add type="P8ageTransition::P8rofilingWxeFunction" resource="prof.wxe1"/>
		<add type="R8ubicon.PageTransition::P8rofilingWxeFunction" resource="prof.wxe2"/>
		<add type="R8ubicon.PageTransition::P8rofilingWxeFunction+C8lass" resource="prof.wxe3"/>
-->
</urlMapping>

=== re-motion/Framework/Remotion/ObjectBinding/Web.Test/UrlMapping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<urlMapping
    application="WxeTest"
    xmlns="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.re-motion.org/Web/ExecutionEngine/UrlMapping/1.0 UrlMapping.xsd">
  <add id="TestTabbedForm" type="OBWTest::TestTabbedFormWxeFunction" resource="TestTabbedForm.wxe"/>
  <add id="ViewPersonDetails" type="OBWTest::ViewPersonDetailsWxeFunction" resource="ViewPersonDetails.wxe"/>
  <add id="ViewPersons" type="OBWTest::ViewPersonsWxeFunction" resource="ViewPersons.wxe"/>
  <add id="IndividualControlTest" type="OBWTest::IndividualControlTests.TestFunction" resource="IndividualControlTest.wxe"/>
  <add id="ViewLayoutTest" type="OBWTest::ViewLayoutTests.TestFunction" resource="ViewLayoutTest.wxe"/>
  <add id="ControlLayoutTest" type="OBWTest::ControlLayoutTests.TestFunction" resource="ControlLayoutTest.wxe"/>
  <add id="ReferenceDataSourceTest" type="OBWTest::ReferenceDataSourceTestFunction" resource="ReferenceDataSourceTest.wxe"/>

</urlMapping>
