=== re-motion/Framework/.nuke/build.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/build",
  "title": "Build Schema",
  "definitions": {
    "build": {
      "type": "object",
      "properties": {
        "AdditionalBuildMetadata": {
          "type": "string",
          "description": "Additional build metadata that is attached to the assembly informational version"
        },
        "AssemblySigningKeyFile": {
          "type": "string",
          "description": "Path to the key file containing the signing key"
        },
        "Configurations": {
          "type": "array",
          "description": "Configuration to build - Default is 'Debug' (local) or 'Release' (server)",
          "items": {
            "type": "string"
          }
        },
        "Continue": {
          "type": "boolean",
          "description": "Indicates to continue a previously failed build attempt"
        },
        "Help": {
          "type": "boolean",
          "description": "Shows the help text for this build assembly"
        },
        "Host": {
          "type": "string",
          "description": "Host for execution. Default is 'automatic'",
          "enum": [
            "AppVeyor",
            "AzurePipelines",
            "Bamboo",
            "Bitbucket",
            "Bitrise",
            "GitHubActions",
            "GitLab",
            "Jenkins",
            "Rider",
            "SpaceAutomation",
            "TeamCity",
            "Terminal",
            "TravisCI",
            "VisualStudio",
            "VSCode"
          ]
        },
        "LogFolder": {
          "type": "string",
          "description": "Path to the log folder where log files are put"
        },
        "NoLogo": {
          "type": "boolean",
          "description": "Disables displaying the NUKE logo"
        },
        "OutputFolder": {
          "type": "string",
          "description": "Path to the output folder where build artifacts are put"
        },
        "Partition": {
          "type": "string",
          "description": "Partition to use on CI"
        },
        "Plan": {
          "type": "boolean",
          "description": "Shows the execution plan (HTML)"
        },
        "Profile": {
          "type": "array",
          "description": "Defines the profiles to load",
          "items": {
            "type": "string"
          }
        },
        "Root": {
          "type": "string",
          "description": "Root directory during build execution"
        },
        "Skip": {
          "type": "array",
          "description": "List of targets to be skipped. Empty list skips all dependencies",
          "items": {
            "type": "string",
            "enum": [
              "Build",
              "CIBuild",
              "Clean",
              "CreateTestMatrix",
              "DetermineBuildMetadata",
              "DetermineProjectMetadata",
              "FullBuild",
              "NightlyBuild",
              "Pack",
              "Restore",
              "Test",
              "VerifyTestParameters"
            ]
          }
        },
        "Solution": {
          "type": "string",
          "description": "Path to a solution file that is automatically loaded"
        },
        "Target": {
          "type": "array",
          "description": "List of targets to be invoked. Default is '{default_target}'",
          "items": {
            "type": "string",
            "enum": [
              "Build",
              "CIBuild",
              "Clean",
              "CreateTestMatrix",
              "DetermineBuildMetadata",
              "DetermineProjectMetadata",
              "FullBuild",
              "NightlyBuild",
              "Pack",
              "Restore",
              "Test",
              "VerifyTestParameters"
            ]
          }
        },
        "TempFolder": {
          "type": "string",
          "description": "Path to the temp folder where temporary build files are put"
        },
        "TestBrowsers": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Chrome",
              "Debug",
              "Docker_Win_NET48",
              "Docker_Win_NET481",
              "Docker_Win_NET8_0",
              "Edge",
              "EnforcedLocalMachine",
              "Firefox",
              "LocalMachine",
              "NET48",
              "NET481",
              "NET8_0",
              "NoBrowser",
              "NoDB",
              "Release",
              "SqlServer2016",
              "SqlServer2017",
              "SqlServer2019",
              "SqlServer2022",
              "SqlServerDefault",
              "x64",
              "x86"
            ]
          }
        },
        "TestConfigurations": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Chrome",
              "Debug",
              "Docker_Win_NET48",
              "Docker_Win_NET481",
              "Docker_Win_NET8_0",
              "Edge",
              "EnforcedLocalMachine",
              "Firefox",
              "LocalMachine",
              "NET48",
              "NET481",
              "NET8_0",
              "NoBrowser",
              "NoDB",
              "Release",
              "SqlServer2016",
              "SqlServer2017",
              "SqlServer2019",
              "SqlServer2022",
              "SqlServerDefault",
              "x64",
              "x86"
            ]
          }
        },
        "TestExecutionRuntimes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Chrome",
              "Debug",
              "Docker_Win_NET48",
              "Docker_Win_NET481",
              "Docker_Win_NET8_0",
              "Edge",
              "EnforcedLocalMachine",
              "Firefox",
              "LocalMachine",
              "NET48",
              "NET481",
              "NET8_0",
              "NoBrowser",
              "NoDB",
              "Release",
              "SqlServer2016",
              "SqlServer2017",
              "SqlServer2019",
              "SqlServer2022",
              "SqlServerDefault",
              "x64",
              "x86"
            ]
          }
        },
        "TestFilter": {
          "type": "string",
          "description": "Executes only tests that match the specified test filter"
        },
        "TestPlatforms": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Chrome",
              "Debug",
              "Docker_Win_NET48",
              "Docker_Win_NET481",
              "Docker_Win_NET8_0",
              "Edge",
              "EnforcedLocalMachine",
              "Firefox",
              "LocalMachine",
              "NET48",
              "NET481",
              "NET8_0",
              "NoBrowser",
              "NoDB",
              "Release",
              "SqlServer2016",
              "SqlServer2017",
              "SqlServer2019",
              "SqlServer2022",
              "SqlServerDefault",
              "x64",
              "x86"
            ]
          }
        },
        "TestSqlServers": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Chrome",
              "Debug",
              "Docker_Win_NET48",
              "Docker_Win_NET481",
              "Docker_Win_NET8_0",
              "Edge",
              "EnforcedLocalMachine",
              "Firefox",
              "LocalMachine",
              "NET48",
              "NET481",
              "NET8_0",
              "NoBrowser",
              "NoDB",
              "Release",
              "SqlServer2016",
              "SqlServer2017",
              "SqlServer2019",
              "SqlServer2022",
              "SqlServerDefault",
              "x64",
              "x86"
            ]
          }
        },
        "TestTargetRuntimes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Chrome",
              "Debug",
              "Docker_Win_NET48",
              "Docker_Win_NET481",
              "Docker_Win_NET8_0",
              "Edge",
              "EnforcedLocalMachine",
              "Firefox",
              "LocalMachine",
              "NET48",
              "NET481",
              "NET8_0",
              "NoBrowser",
              "NoDB",
              "Release",
              "SqlServer2016",
              "SqlServer2017",
              "SqlServer2019",
              "SqlServer2022",
              "SqlServerDefault",
              "x64",
              "x86"
            ]
          }
        },
        "UseReleaseVersioning": {
          "type": "boolean",
          "description": "Uses release instead of debug versioning when determining the build versions"
        },
        "Verbosity": {
          "type": "string",
          "description": "Logging verbosity during build execution. Default is 'Normal'",
          "enum": [
            "Minimal",
            "Normal",
            "Quiet",
            "Verbose"
          ]
        }
      }
    }
  }
}

=== re-motion/Framework/.nuke/parameters.ci.json
{
  "$schema": "./build.schema.json",
  "Solution": "Remotion.sln",
  "Target": [ "CIBuild" ],
  "TestConfigurations": [ "Debug" ],
  "TestExecutionRuntimes": [ "Docker_Win_NET48" ],
  "TestPlatforms": [ "x86" ],
  "TestTargetRuntimes": [ "NET48" ],
  "TestBrowsers": [ "NoBrowser", "Chrome" ],
  "TestSqlServers": [ "NoDB", "SqlServer2016" ],
  "TestFilter": "TestCategory!=LongRunning&TestCategory!=ControlSelectorTest"
}

=== re-motion/Framework/.nuke/parameters.nightly.json
{
  "$schema": "./build.schema.json",
  "Solution": "Remotion.sln",
  "Target": [ "NightlyBuild" ],
  "TestConfigurations": [ "Debug", "Release" ],
  "TestExecutionRuntimes": [ "Docker_Win_NET48", "Docker_Win_NET481" ],
  "TestPlatforms": [ "x86", "x64" ],
  "TestTargetRuntimes": [ "NET48", "NET481" ],
  "TestBrowsers": [ "NoBrowser", "Chrome", "Edge", "Firefox" ],
  "TestSqlServers": [ "NoDB", "SqlServer2016", "SqlServer2017", "SqlServer2019", "SqlServer2022" ]
}

=== re-motion/Framework/.nuke/parameters.full.json
{
  "$schema": "./build.schema.json",
  "Solution": "Remotion.sln",
  "Target": [ "FullBuild" ],
  "TestConfigurations": [ "Debug", "Release" ],
  "TestExecutionRuntimes": [ "Docker_Win_NET48", "Docker_Win_NET481" ],
  "TestPlatforms": [ "x86", "x64" ],
  "TestTargetRuntimes": [ "NET48", "NET481" ],
  "TestBrowsers": [ "NoBrowser", "Chrome", "Edge", "Firefox" ],
  "TestSqlServers": [ "NoDB", "SqlServer2016", "SqlServer2017", "SqlServer2019", "SqlServer2022" ]
}
