=== re-motion/Framework/Remotion/Data/DomainObjects/Schemas/Queries.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:q="http://www.re-motion.org/Data/DomainObjects/Queries/2.0"
    xmlns:t="http://www.re-motion.org/Data/DomainObjects/Types" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    targetNamespace="http://www.re-motion.org/Data/DomainObjects/Queries/2.0"
    xml:lang="en">

  <!-- TODO: Import should contain schemaLocation to ensure application developer can check its mapping during design time. 
             Before this is done it should be verified that schemaLocation there is no problem when XSD is used as embedded ressource during run time. -->
  <xs:import namespace="http://www.re-motion.org/Data/DomainObjects/Types" />

  <xs:element name="queries">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="query" type="q:queryType" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>

    <xs:key name="queryKey">
      <xs:selector xpath="q:query" />
      <xs:field xpath="@id" />
    </xs:key>

  </xs:element>

  <xs:complexType name="queryType">
    <xs:sequence>
      <xs:element name="storageGroupType" type="t:requiredStringType" minOccurs="0" />
      <xs:element name="statement" type="t:requiredStringType" />
      <xs:element name="collectionType" type="t:requiredStringType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="collection-readonly" />
          <xs:enumeration value="scalar-readonly" />
          <xs:enumeration value="custom-readonly" />
          <xs:enumeration value="collection-readwrite" />
          <xs:enumeration value="scalar-readwrite" />
          <xs:enumeration value="custom-readwrite" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:schema>

=== re-motion/Framework/Remotion/Data/DomainObjects.UnitTests/QueriesForLoaderTestDuplicate.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<queries 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Queries/2.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Queries/2.0 ..\DomainObjects\Schemas\Queries.xsd">

  <query id="OrderQueryWithCustomCollectionType" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="OrderQueryWithObjectListOfOrder" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.ObjectList`1[[Remotion.Data.DomainObjects.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.UnitTests]], Remotion.Data.DomainObjects</collectionType>
  </query>

  <query id="CustomerTypeQuery" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Company].* from [Company] where [CustomerType] = @customerType order by [Name] asc;</statement>
  </query>

  <query id="OrderSumQuery" type="scalar-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select sum(quantity) from [Order] where [CustomerID] = @customerID;</statement>
  </query>

</queries>

=== re-motion/Framework/Remotion/Data/DomainObjects.UnitTests/QueriesForStandardMapping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<queries 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Queries/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Queries/1.0 ..\..\DomainObjects\Schemas\Queries.xsd">

  <query id="QueryWithoutParameter" type="scalar">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select 42</statement>
  </query>

  <query id="OrderNoSumByCustomerNameQuery" type="scalar">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>
      select sum([OrderNo])
      from [Order] inner join [Company] on [CustomerID] = [Company].[ID]
      where [Company].[Name] = @customerName;
    </statement>
  </query>

  <query id="OrderNoSumForMultipleCustomers" type="scalar">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>
      select sum([OrderNo])
      from [Order] inner join [Company] on [CustomerID] = [Company].[ID]
      where [Company].[Name] in ({companyNames});
    </statement>
  </query>

  <query id="BulkUpdateQuery" type="scalar">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>
      update [Order] set [DeliveryDate] = '2006/01/01' where [CustomerID] = @customerID;
      select @@ROWCOUNT;
    </statement>
  </query>

  <query id="OrderQuery" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] where [CustomerID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="OrderByOfficialQuery" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] where [OfficialID] = @officialID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="CustomerTypeQuery" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select * from [Company] where [CustomerType] = @customerType order by [Name] asc;</statement>
  </query>

  <query id="QueryWithDuplicates" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>SELECT [Order].* FROM [OrderItem] INNER JOIN [Order] ON [OrderItem].[OrderID] = [Order].[ID] WHERE [Order].[OrderNo] = 1;</statement>
  </query>

  <query id="QueryWithSpecificCollectionType" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select * from [Order];</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests::TestDomain.SpecificOrderCollection</collectionType>
  </query>

  <query id="QueryWithAllDataTypes" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <!-- SQL statement with invalid XML character value. -->
    <statement>
       <![CDATA[
        set ANSI_NULLS OFF;
        select * from TableWithAllDataTypes where 
          [Boolean] = @boolean and
          [Byte] = @byte and
          [Date] = @date and
          [DateTime] = @dateTime and
          [Decimal] = @decimal and
          [Double] > @doubleLowerBound and [Double] < @doubleUpperBound and
          [Enum] = @enum and
          [ExtensibleEnum] = @extensibleEnum and
          [Guid] = @guid and
          [Int16] = @int16 and
          [Int32] = @int32 and
          [Int64] = @int64 and
          [Single] > @singleLowerBound and [Single] < @singleUpperBound and
          [String] = @string and
          [StringWithoutMaxLength] = @stringWithoutMaxLength and -- TODO
          [Binary] = @binary and -- TODO
          -- Note: StringWithoutMaxLength cannot be used here, because it is of type 'text'.
          -- Note: Binary cannot be used here, because it is of type 'image'.
          [NaBoolean] = @naBoolean and
          [NaByte] = @naByte and
          [NaDate] = @naDate and
          [NaDateTime] = @naDateTime and
          [NaDecimal] = @naDecimal and
          [NaDouble] > @naDoubleLowerBound and [NaDouble] < @naDoubleUpperBound and
          [NaEnum] = @naEnum and
          [NaFlags] = @naFlags and -- TODO
          [NaGuid] = @naGuid and
          [NaInt16] = @naInt16 and
          [NaInt32] = @naInt32 and
          [NaInt64] = @naInt64 and
          [NaSingle] > @naSingleLowerBound and [NaSingle] < @naSingleUpperBound and
          [StringWithNullValue] = @stringWithNullValue and
          [ExtensibleEnumWithNullValue] = @extensibleEnumWithNullValue and
          [NaBooleanWithNullValue] = @naBooleanWithNullValue and 
          [NaByteWithNullValue] = @naByteWithNullValue and 
          [NaDateWithNullValue] = @naDateWithNullValue and
          [NaDateTimeWithNullValue] = @naDateTimeWithNullValue and
          [NaDecimalWithNullValue] = @naDecimalWithNullValue and 	        
          [NaDoubleWithNullValue] = @naDoubleWithNullValue and
          [NaEnumWithNullValue] = @naEnumWithNullValue and
          [NaFlagsWithNullValue] = @naFlagsWithNullValue and -- TODO
          [NaGuidWithNullValue] = @naGuidWithNullValue and
          [NaInt16WithNullValue] = @naInt16WithNullValue and
          [NaInt32WithNullValue] = @naInt32WithNullValue and
          [NaInt64WithNullValue] = @naInt64WithNullValue and
          [NaSingleWithNullValue] = @naSingleWithNullValue and
          [NullableBinary] = @nullableBinaryWithNullValue; -- TODO 
      ]]>      
    </statement>
  </query>

  <query id="StoredProcedureQuery" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>rpf_testSPQuery</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="StoredProcedureQueryWithParameter" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>exec rpf_testSPQueryWithParameter @customerID</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="FakeQuery" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>SELECT "Dummy"</statement>
    <collectionType>Remotion.Data.DomainObjects::DomainObjectCollection</collectionType>
  </query>

  <query id="CustomQuery" type="custom">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>SELECT String, Int16, Boolean, Enum, ExtensibleEnum  FROM [TableWithAllDataTypes]</statement>
  </query>

  <query id="OrderQueryWithDomainObjectCollectionType" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select * from [Order];</statement>
    <collectionType>Remotion.Data.DomainObjects::DomainObjectCollection</collectionType>
  </query>

</queries>

=== re-motion/Framework/Remotion/Data/DomainObjects.UnitTests/QueriesForLoaderTest2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<queries 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Queries/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Queries/1.0 ..\DomainObjects\Schemas\Queries.xsd">

  <query id="OrderQueryWithCustomCollectionType2" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="OrderQueryWithObjectListOfOrder2" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.ObjectList`1[[Remotion.Data.DomainObjects.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.UnitTests]], Remotion.Data.DomainObjects</collectionType>
  </query>

  <query id="CustomerTypeQuery2" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Company].* from [Company] where [CustomerType] = @customerType order by [Name] asc;</statement>
  </query>

  <query id="OrderSumQuery2" type="scalar">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select sum(quantity) from [Order] where [CustomerID] = @customerID;</statement>
  </query>

</queries>
